job('First-Maven-Project-Via-DSL') {

    description("First Maven job generated by the DSL project")

    scm {
        git("https://github.com/frazgorsi160/Pipeline.git", 'main')
    }

    triggers {
        scm('H/2 * * * *')
    }

    steps {
        maven('clean package', 'Jenkins_Upgradev3-master/maven-samples/single-module/pom.xml')
    }

    publishers {
        archiveArtifacts '**/*.jar'
    }
}
