job('First-Maven-Project-Via-DSL') {

    description("First Maven job generated by the DSL project is a small Maven project hosted on github")

    scm {
        git {
            remote {
                url("https://github.com/frazgorsi160/Pipeline.git")
            }
            branch("main")

            // ✅ IMPORTANT FIX: disable per-build tagging
            extensions {
                disableTagging()
            }
        }
    }

    triggers {
        scm('* * * * *')
    }

    steps {
        maven('test', 'Jenkins_Upgradev3-master/maven-samples/single-module/pom.xml')
    }

    publishers {
        archiveArtifacts '**/*.jar'
    }
}
