job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL project is a small Maven project hosted on github")
    scm {
        git("https://github.com/frazgorsi160/Pipeline.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('test', 'Jenkins_Upgradev3-master/maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
